<?php
function get_zone( $phone ) {
	static $zone;
	if (!isset($zone)) {
		$zone = array(
			array('id' => 2, 'prefix' => '375447', 'country' => 'Беларусь', 'iso' => 'BY'),
			array('id' => 2, 'prefix' => '375445', 'country' => 'Беларусь', 'iso' => 'BY'),
			array('id' => 2, 'prefix' => '375444', 'country' => 'Беларусь', 'iso' => 'BY'),
			array('id' => 2, 'prefix' => '375336', 'country' => 'Беларусь', 'iso' => 'BY'),
			array('id' => 2, 'prefix' => '375259', 'country' => 'Беларусь', 'iso' => 'BY'),
			array('id' => 4, 'prefix' => '38099', 'country' => 'Украина', 'iso' => 'UA'),
			array('id' => 4, 'prefix' => '38098', 'country' => 'Украина', 'iso' => 'UA'),
			array('id' => 4, 'prefix' => '38097', 'country' => 'Украина', 'iso' => 'UA'),
			array('id' => 4, 'prefix' => '38096', 'country' => 'Украина', 'iso' => 'UA'),
			array('id' => 4, 'prefix' => '38095', 'country' => 'Украина', 'iso' => 'UA'),
			array('id' => 4, 'prefix' => '38094', 'country' => 'Украина', 'iso' => 'UA'),
			array('id' => 4, 'prefix' => '38093', 'country' => 'Украина', 'iso' => 'UA'),
			array('id' => 4, 'prefix' => '38092', 'country' => 'Украина', 'iso' => 'UA'),
			array('id' => 4, 'prefix' => '38091', 'country' => 'Украина', 'iso' => 'UA'),
			array('id' => 4, 'prefix' => '38068', 'country' => 'Украина', 'iso' => 'UA'),
			array('id' => 4, 'prefix' => '38067', 'country' => 'Украина', 'iso' => 'UA'),
			array('id' => 4, 'prefix' => '38066', 'country' => 'Украина', 'iso' => 'UA'),
			array('id' => 4, 'prefix' => '38063', 'country' => 'Украина', 'iso' => 'UA'),
			array('id' => 4, 'prefix' => '38050', 'country' => 'Украина', 'iso' => 'UA'),
			array('id' => 4, 'prefix' => '38039', 'country' => 'Украина', 'iso' => 'UA'),
			array('id' => 2, 'prefix' => '37529', 'country' => 'Беларусь', 'iso' => 'BY'),
			array('id' => 2, 'prefix' => '37525', 'country' => 'Беларусь', 'iso' => 'BY'),	
			array('id' => 2, 'prefix' => '7940', 'country' => 'Казахстан', 'iso' => 'KZ'),
			array('id' => 2, 'prefix' => '7778', 'country' => 'Казахстан', 'iso' => 'KZ'), // 2013-04-05
			array('id' => 2, 'prefix' => '7777', 'country' => 'Казахстан', 'iso' => 'KZ'),
			array('id' => 2, 'prefix' => '7775', 'country' => 'Казахстан', 'iso' => 'KZ'),
			array('id' => 2, 'prefix' => '7763', 'country' => 'Казахстан', 'iso' => 'KZ'),
			array('id' => 2, 'prefix' => '7762', 'country' => 'Казахстан', 'iso' => 'KZ'),
			array('id' => 2, 'prefix' => '7760', 'country' => 'Казахстан', 'iso' => 'KZ'),
			array('id' => 2, 'prefix' => '7750', 'country' => 'Казахстан', 'iso' => 'KZ'),
			array('id' => 2, 'prefix' => '7705', 'country' => 'Казахстан', 'iso' => 'KZ'),
			array('id' => 2, 'prefix' => '7702', 'country' => 'Казахстан', 'iso' => 'KZ'),
			array('id' => 2, 'prefix' => '7701', 'country' => 'Казахстан', 'iso' => 'KZ'),
			array('id' => 5, 'prefix' => '3712', 'country' => 'Латвия', 'iso' => 'LV'),
			array('id' => 6, 'prefix' => '1869', 'country' => 'Сент-Китс и Невис', 'iso' => 'KN'),
			array('id' => 2, 'prefix' => '1868', 'country' => 'Тринидад и Тобаго', 'iso' => 'TT'),
			array('id' => 2, 'prefix' => '1829', 'country' => 'Доминиканская Республика', 'iso' => 'DO'),
			array('id' => 6, 'prefix' => '1787', 'country' => 'Пуэрто-Рико', 'iso' => 'PR'),
			array('id' => 2, 'prefix' => '1784', 'country' => 'Сент-Винсент и Гренадины', 'iso' => 'VC'),
			array('id' => 2, 'prefix' => '1767', 'country' => 'Доминика', 'iso' => 'DM'),
			array('id' => 2, 'prefix' => '1758', 'country' => 'Сент-Люсия', 'iso' => 'LC'),
			array('id' => 5, 'prefix' => '1664', 'country' => 'Монтсеррат', 'iso' => 'MS'),
			array('id' => 2, 'prefix' => '1649', 'country' => 'Острова Тёркс и Кайкос', 'iso' => 'TC'),
			array('id' => 2, 'prefix' => '1473', 'country' => 'Гренада', 'iso' => 'GD'),
			array('id' => 2, 'prefix' => '1441', 'country' => 'Бермудские острова', 'iso' => 'BM'),
			array('id' => 2, 'prefix' => '1345', 'country' => 'Каймановы острова', 'iso' => 'KY'),
			array('id' => 3, 'prefix' => '1284', 'country' => 'Британские Виргинские острова', 'iso' => 'VG'),
			array('id' => 3, 'prefix' => '1268', 'country' => 'Антигуа и Барбуда', 'iso' => 'AG'),
			array('id' => 3, 'prefix' => '1264', 'country' => 'Ангилья', 'iso' => 'AI'),
			array('id' => 2, 'prefix' => '1246', 'country' => 'Барбадос', 'iso' => 'BB'),
			array('id' => 2, 'prefix' => '1242', 'country' => 'Багамы', 'iso' => 'BS'),
			array('id' => 2, 'prefix' => '998', 'country' => 'Узбекистан', 'iso' => 'UZ'),
			array('id' => 2, 'prefix' => '996', 'country' => 'Кыргызстан Киргизия', 'iso' => 'KG'),
			array('id' => 2, 'prefix' => '995', 'country' => 'Грузия', 'iso' => 'GE'),
			array('id' => 2, 'prefix' => '994', 'country' => 'Азербайджан', 'iso' => 'AZ'),
			array('id' => 2, 'prefix' => '993', 'country' => 'Туркмения', 'iso' => 'TM'),
			array('id' => 2, 'prefix' => '992', 'country' => 'Таджикистан', 'iso' => 'TJ'),
			array('id' => 5, 'prefix' => '977', 'country' => 'Непал', 'iso' => 'NP'),
			array('id' => 2, 'prefix' => '976', 'country' => 'Монголия', 'iso' => 'MN'),
			array('id' => 2, 'prefix' => '975', 'country' => 'Бутан', 'iso' => 'BT'),
			array('id' => 5, 'prefix' => '974', 'country' => 'Катар', 'iso' => 'QA'),
			array('id' => 2, 'prefix' => '973', 'country' => 'Бахрейн', 'iso' => 'BH'),
			array('id' => 6, 'prefix' => '972', 'country' => 'Израиль', 'iso' => 'IL'),
			array('id' => 2, 'prefix' => '971', 'country' => 'Объединенные Арабские Эмираты (ОАЭ)', 'iso' => 'AE'),
			array('id' => 2, 'prefix' => '968', 'country' => 'Оман', 'iso' => 'OM'),
			array('id' => 2, 'prefix' => '967', 'country' => 'Йемен', 'iso' => 'YE'),
			array('id' => 2, 'prefix' => '966', 'country' => 'Саудовская Аравия', 'iso' => 'SA'),
			array('id' => 5, 'prefix' => '965', 'country' => 'Кувейт', 'iso' => 'KW'),
			array('id' => 2, 'prefix' => '964', 'country' => 'Ирак', 'iso' => 'IQ'),
			array('id' => 2, 'prefix' => '963', 'country' => 'Сирия', 'iso' => 'SY'),
			array('id' => 3, 'prefix' => '962', 'country' => 'Иордания', 'iso' => 'JO'),
			array('id' => 2, 'prefix' => '961', 'country' => 'Ливан', 'iso' => 'LB'),
			array('id' => 2, 'prefix' => '960', 'country' => 'Мальдивы', 'iso' => 'MV'),
			array('id' => 2, 'prefix' => '886', 'country' => 'Тайвань (Китай)', 'iso' => 'TW'),
			array('id' => 2, 'prefix' => '880', 'country' => 'Бангладеш', 'iso' => 'BD'),
			array('id' => 5, 'prefix' => '856', 'country' => 'Лаос', 'iso' => 'LA'),
			array('id' => 2, 'prefix' => '855', 'country' => 'Камбоджа', 'iso' => 'KH'),
			array('id' => 6, 'prefix' => '853', 'country' => 'Макао', 'iso' => 'MO'),
			array('id' => 2, 'prefix' => '852', 'country' => 'Гонконг', 'iso' => 'HK'),
			array('id' => 2, 'prefix' => '770', 'country' => 'Казахстан', 'iso' => 'KZ'),
			array('id' => 2, 'prefix' => '689', 'country' => 'Французская Полинезия', 'iso' => 'PF'),
			array('id' => 2, 'prefix' => '687', 'country' => 'Новая Каледония', 'iso' => 'NC'),
			array('id' => 5, 'prefix' => '685', 'country' => 'Самоа', 'iso' => 'WS'),
			array('id' => 2, 'prefix' => '682', 'country' => 'Острова Кука', 'iso' => 'CK'),
			array('id' => 2, 'prefix' => '679', 'country' => 'Фиджи', 'iso' => 'FJ'),
			array('id' => 5, 'prefix' => '678', 'country' => 'Вануату', 'iso' => 'VU'),
			array('id' => 2, 'prefix' => '676', 'country' => 'Тонга', 'iso' => 'TO'),
			array('id' => 2, 'prefix' => '675', 'country' => 'Папуа-Новая Гвинея', 'iso' => 'PG'),
			array('id' => 2, 'prefix' => '673', 'country' => 'Бруней-Даруссалам', 'iso' => 'BN'),
			array('id' => 2, 'prefix' => '599', 'country' => 'Нидерландские Антилы', 'iso' => 'AN'),
			array('id' => 2, 'prefix' => '598', 'country' => 'Уругвай', 'iso' => 'UY'),
			array('id' => 2, 'prefix' => '597', 'country' => 'Суринам', 'iso' => 'SR'),
			array('id' => 4, 'prefix' => '596', 'country' => 'Мартиника', 'iso' => 'MQ'),
			array('id' => 2, 'prefix' => '595', 'country' => 'Парагвай', 'iso' => 'PY'),
			array('id' => 2, 'prefix' => '594', 'country' => 'Французская Гвиана', 'iso' => 'GF'),
			array('id' => 3, 'prefix' => '593', 'country' => 'Эквадор', 'iso' => 'EC'),
			array('id' => 2, 'prefix' => '592', 'country' => 'Гайана', 'iso' => 'GY'),
			array('id' => 3, 'prefix' => '591', 'country' => 'Боливия', 'iso' => 'BO'),
			array('id' => 2, 'prefix' => '509', 'country' => 'Гаити', 'iso' => 'HT'),
			array('id' => 6, 'prefix' => '507', 'country' => 'Панама', 'iso' => 'PA'),
			array('id' => 4, 'prefix' => '506', 'country' => 'Коста-Рика', 'iso' => 'CR'),
			array('id' => 5, 'prefix' => '505', 'country' => 'Никарагуа', 'iso' => 'NI'),
			array('id' => 2, 'prefix' => '504', 'country' => 'Гондурас', 'iso' => 'HN'),
			array('id' => 3, 'prefix' => '503', 'country' => 'Эль-Сальвадор', 'iso' => 'SV'),
			array('id' => 2, 'prefix' => '502', 'country' => 'Гватемала', 'iso' => 'GT'),
			array('id' => 2, 'prefix' => '501', 'country' => 'Белиз', 'iso' => 'BZ'),
			array('id' => 2, 'prefix' => '500', 'country' => 'Фолклендские (Мальвинские) острова', 'iso' => 'FK'),
			array('id' => 3, 'prefix' => '423', 'country' => 'Лихтенштейн', 'iso' => 'LI'),
			array('id' => 2, 'prefix' => '421', 'country' => 'Словакия', 'iso' => 'SK'),
			array('id' => 3, 'prefix' => '420', 'country' => 'Чехия Чешская Республика', 'iso' => 'CZ'),
			array('id' => 2, 'prefix' => '389', 'country' => 'Республика Македония', 'iso' => 'MK'),
			array('id' => 2, 'prefix' => '387', 'country' => 'Босния и Герцеговина', 'iso' => 'BA'),
			array('id' => 3, 'prefix' => '386', 'country' => 'Словения', 'iso' => 'SI'),
			array('id' => 3, 'prefix' => '385', 'country' => 'Хорватия', 'iso' => 'HR'),
			array('id' => 2, 'prefix' => '382', 'country' => 'Черногория', 'iso' => 'ME'),
			array('id' => 2, 'prefix' => '381', 'country' => 'Сербия', 'iso' => 'RS'),
			array('id' => 5, 'prefix' => '378', 'country' => 'Сан-Марино', 'iso' => 'SM'),
			array('id' => 2, 'prefix' => '377', 'country' => 'Монако', 'iso' => 'MC'),
			array('id' => 2, 'prefix' => '376', 'country' => 'Андорра', 'iso' => 'AD'),
			array('id' => 6, 'prefix' => '374', 'country' => 'Армения', 'iso' => 'AM'),
			array('id' => 2, 'prefix' => '373', 'country' => 'Молдавия Молдова', 'iso' => 'MD'),
			array('id' => 2, 'prefix' => '372', 'country' => 'Эстония', 'iso' => 'EE'),
			array('id' => 2, 'prefix' => '370', 'country' => 'Литва', 'iso' => 'LT'),
			array('id' => 3, 'prefix' => '359', 'country' => 'Болгария', 'iso' => 'BG'),
			array('id' => 2, 'prefix' => '358', 'country' => 'Финляндия', 'iso' => 'FI'),
			array('id' => 2, 'prefix' => '357', 'country' => 'Кипр', 'iso' => 'CY'),
			array('id' => 2, 'prefix' => '356', 'country' => 'Мальта', 'iso' => 'MT'),
			array('id' => 2, 'prefix' => '355', 'country' => 'Албания', 'iso' => 'AL'),
			array('id' => 2, 'prefix' => '354', 'country' => 'Исландия', 'iso' => 'IS'),
			array('id' => 2, 'prefix' => '353', 'country' => 'Ирландия', 'iso' => 'IE'),
			array('id' => 2, 'prefix' => '352', 'country' => 'Люксембург', 'iso' => 'LU'),
			array('id' => 5, 'prefix' => '351', 'country' => 'Португалия', 'iso' => 'PT'),
			array('id' => 2, 'prefix' => '350', 'country' => 'Гибралтар', 'iso' => 'GI'),
			array('id' => 2, 'prefix' => '299', 'country' => 'Гренландия', 'iso' => 'GL'),
			array('id' => 2, 'prefix' => '298', 'country' => 'Фарерские острова', 'iso' => 'FO'),
			array('id' => 2, 'prefix' => '297', 'country' => 'Аруба', 'iso' => 'AW'),
			array('id' => 2, 'prefix' => '269', 'country' => 'Коморы', 'iso' => 'KM'),
			array('id' => 2, 'prefix' => '268', 'country' => 'Свазиленд', 'iso' => 'SZ'),
			array('id' => 3, 'prefix' => '267', 'country' => 'Ботсвана', 'iso' => 'BW'),
			array('id' => 2, 'prefix' => '266', 'country' => 'Лесото', 'iso' => 'LS'),
			array('id' => 2, 'prefix' => '265', 'country' => 'Малави', 'iso' => 'MW'),
			array('id' => 2, 'prefix' => '264', 'country' => 'Намибия', 'iso' => 'NA'),
			array('id' => 2, 'prefix' => '263', 'country' => 'Зимбабве', 'iso' => 'ZW'),
			array('id' => 2, 'prefix' => '262', 'country' => 'Реюньон', 'iso' => 'RE'),
			array('id' => 2, 'prefix' => '261', 'country' => 'Мадагаскар', 'iso' => 'MG'),
			array('id' => 2, 'prefix' => '260', 'country' => 'Замбия', 'iso' => 'ZM'),
			array('id' => 2, 'prefix' => '258', 'country' => 'Мозамбик', 'iso' => 'MZ'),
			array('id' => 2, 'prefix' => '257', 'country' => 'Бурунди', 'iso' => 'BI'),
			array('id' => 2, 'prefix' => '256', 'country' => 'Уганда', 'iso' => 'UG'),
			array('id' => 2, 'prefix' => '255', 'country' => 'Танзания', 'iso' => 'TZ'),
			array('id' => 5, 'prefix' => '254', 'country' => 'Кения', 'iso' => 'KE'),
		
			array('id' => 2, 'prefix' => '253', 'country' => 'Джибути', 'iso' => 'DJ'),
			array('id' => 2, 'prefix' => '251', 'country' => 'Эфиопия', 'iso' => 'ET'),
			array('id' => 2, 'prefix' => '250', 'country' => 'Руанда', 'iso' => 'RW'),
			array('id' => 2, 'prefix' => '249', 'country' => 'Судан', 'iso' => 'SD'),
			array('id' => 2, 'prefix' => '248', 'country' => 'Сейшелы', 'iso' => 'SC'),
			array('id' => 2, 'prefix' => '245', 'country' => 'Гвинея-Бисау', 'iso' => 'GW'),
			array('id' => 2, 'prefix' => '244', 'country' => 'Ангола', 'iso' => 'AO'),
			array('id' => 2, 'prefix' => '242', 'country' => 'Конго', 'iso' => 'CG'),
			array('id' => 2, 'prefix' => '241', 'country' => 'Габон', 'iso' => 'GA'),
			array('id' => 2, 'prefix' => '240', 'country' => 'Экваториальная Гвинея', 'iso' => 'GQ'),
			array('id' => 4, 'prefix' => '238', 'country' => 'Кабо-Верде', 'iso' => 'CV'),
			array('id' => 2, 'prefix' => '237', 'country' => 'Камерун', 'iso' => 'CM'),
			array('id' => 2, 'prefix' => '236', 'country' => 'Центральноафриканская Республика (ЦАР)', 'iso' => 'CF'),
			array('id' => 2, 'prefix' => '235', 'country' => 'Чад', 'iso' => 'TD'),
			array('id' => 5, 'prefix' => '234', 'country' => 'Нигерия', 'iso' => 'NG'),
			array('id' => 2, 'prefix' => '233', 'country' => 'Гана', 'iso' => 'GH'),
			array('id' => 2, 'prefix' => '232', 'country' => 'Сьерра-Леоне', 'iso' => 'SL'),
			array('id' => 2, 'prefix' => '231', 'country' => 'Либерия', 'iso' => 'LR'),
			array('id' => 2, 'prefix' => '230', 'country' => 'Маврикий', 'iso' => 'MU'),
			array('id' => 2, 'prefix' => '229', 'country' => 'Бенин', 'iso' => 'BJ'),
			array('id' => 2, 'prefix' => '228', 'country' => 'Того', 'iso' => 'TG'),
			array('id' => 5, 'prefix' => '227', 'country' => 'Нигер', 'iso' => 'NE'),
			array('id' => 4, 'prefix' => '226', 'country' => 'Буркина-Фасо', 'iso' => 'BF'),
			array('id' => 2, 'prefix' => '224', 'country' => 'Гвинея', 'iso' => 'GN'),
			array('id' => 2, 'prefix' => '223', 'country' => 'Мали', 'iso' => 'ML'),
			array('id' => 2, 'prefix' => '222', 'country' => 'Мавритания', 'iso' => 'MR'),
			array('id' => 2, 'prefix' => '221', 'country' => 'Сенегал', 'iso' => 'SN'),
			array('id' => 2, 'prefix' => '220', 'country' => 'Гамбия', 'iso' => 'GM'),
			array('id' => 2, 'prefix' => '218', 'country' => 'Ливия', 'iso' => 'LY'),
			array('id' => 2, 'prefix' => '216', 'country' => 'Тунис', 'iso' => 'TN'),
			array('id' => 2, 'prefix' => '213', 'country' => 'Алжир', 'iso' => 'DZ'),
			array('id' => 2, 'prefix' => '212', 'country' => 'Марокко', 'iso' => 'MA'),
			array('id' => 3, 'prefix' => '98', 'country' => 'Иран', 'iso' => 'IR'),
			array('id' => 2, 'prefix' => '94', 'country' => 'Шри-Ланка', 'iso' => 'LK'),
			array('id' => 2, 'prefix' => '92', 'country' => 'Пакистан', 'iso' => 'PK'),
			array('id' => 2, 'prefix' => '91', 'country' => 'Индия', 'iso' => 'IN'),
			array('id' => 3, 'prefix' => '90', 'country' => 'Турция', 'iso' => 'TR'),
			array('id' => 4, 'prefix' => '86', 'country' => 'Китай (КНР)', 'iso' => 'CN'),
			array('id' => 2, 'prefix' => '84', 'country' => 'Вьетнам', 'iso' => 'VN'),
			array('id' => 2, 'prefix' => '82', 'country' => 'Южная Корея', 'iso' => 'KR'),
			array('id' => 2, 'prefix' => '81', 'country' => 'Япония', 'iso' => 'JP'),
			array('id' => 2, 'prefix' => '66', 'country' => 'Таиланд', 'iso' => 'TH'),
			array('id' => 2, 'prefix' => '65', 'country' => 'Сингапур', 'iso' => 'SG'),
			array('id' => 2, 'prefix' => '64', 'country' => 'Новая Зеландия', 'iso' => 'NZ'),
			array('id' => 3, 'prefix' => '63', 'country' => 'Филиппины', 'iso' => 'PH'),
			array('id' => 2, 'prefix' => '62', 'country' => 'Индонезия', 'iso' => 'ID'),
			array('id' => 3, 'prefix' => '61', 'country' => 'Австралия', 'iso' => 'AU'),
			array('id' => 3, 'prefix' => '60', 'country' => 'Малайзия', 'iso' => 'MY'),
			array('id' => 3, 'prefix' => '58', 'country' => 'Венесуэла', 'iso' => 'VE'),
			array('id' => 3, 'prefix' => '57', 'country' => 'Колумбия', 'iso' => 'CO'),
			array('id' => 3, 'prefix' => '56', 'country' => 'Чили', 'iso' => 'CL'),
			array('id' => 5, 'prefix' => '55', 'country' => 'Бразилия', 'iso' => 'BR'),
			array('id' => 3, 'prefix' => '54', 'country' => 'Аргентина', 'iso' => 'AR'),
			array('id' => 2, 'prefix' => '53', 'country' => 'Куба', 'iso' => 'CU'),
			array('id' => 6, 'prefix' => '52', 'country' => 'Мексика', 'iso' => 'MX'),
			array('id' => 2, 'prefix' => '51', 'country' => 'Перу', 'iso' => 'PE'),
			array('id' => 4, 'prefix' => '49', 'country' => 'Германия', 'iso' => 'DE'),
			array('id' => 3, 'prefix' => '48', 'country' => 'Польша', 'iso' => 'PL'),
			array('id' => 3, 'prefix' => '47', 'country' => 'Норвегия', 'iso' => 'NO'),
			array('id' => 6, 'prefix' => '46', 'country' => 'Швеция', 'iso' => 'SE'),
			array('id' => 2, 'prefix' => '45', 'country' => 'Дания', 'iso' => 'DK'),
			array('id' => 6, 'prefix' => '44', 'country' => 'Великобритания', 'iso' => 'GB'),
			array('id' => 4, 'prefix' => '43', 'country' => 'Австрия', 'iso' => 'AT'),
			array('id' => 4, 'prefix' => '41', 'country' => 'Швейцария', 'iso' => 'CH'),
			array('id' => 5, 'prefix' => '40', 'country' => 'Румыния', 'iso' => 'RO'),
			array('id' => 4, 'prefix' => '39', 'country' => 'Италия', 'iso' => 'IT'),
			array('id' => 4, 'prefix' => '36', 'country' => 'Венгрия', 'iso' => 'HU'),
			array('id' => 5, 'prefix' => '34', 'country' => 'Испания', 'iso' => 'ES'),
			array('id' => 5, 'prefix' => '33', 'country' => 'Франция', 'iso' => 'FR'),
			array('id' => 3, 'prefix' => '32', 'country' => 'Бельгия', 'iso' => 'BE'),
			array('id' => 4, 'prefix' => '31', 'country' => 'Голландия Нидерланды', 'iso' => 'NL'),
			array('id' => 3, 'prefix' => '30', 'country' => 'Греция', 'iso' => 'GR'),
			array('id' => 2, 'prefix' => '27', 'country' => 'Южная Африка (ЮАР)', 'iso' => 'ZA'),
			array('id' => 2, 'prefix' => '20', 'country' => 'Египет', 'iso' => 'EG'),
			array('id' => 3, 'prefix' => '1', 'country' => 'США и Канада', 'iso' => 'US'),
			array('id' => 1, 'prefix' => '79', 'country' => 'Россия', 'iso' => 'RU')
		);
		// длинные префиксы сверху
		$plen = array();
		foreach( $zone as $k => $v )
			$plen[ $k ] = strlen( $v['prefix'] );
		array_multisort( $plen, SORT_DESC, $zone);
	}
	$phone = (string) $phone;
	if (!preg_match('~^\d{10,15}$~',$phone))
		return false;
		
	if (substr($phone,0,2) === '89') // автоисправление 8
		$phone = '7'.substr($phone,1);
	if (substr($phone,0,2) === '87') // автоисправление 8 kz
		$phone = '7'.substr($phone,1);
	
	foreach ( $zone as $z ) {
		if (strpos($phone, $z['prefix']) === 0)
			return $z;
	}
	return false;
}
?>